import { Router } from "express";
import * as userController from "../controllers/user.js";
import { verifyJWT } from "../utils/jwt.js";
import { userMiddleware } from "../utils/userMiddleware.js";
import { upload } from "../utils/multer.js";

export const userRoutes = Router();

userRoutes.get('/', verifyJWT, userController.getUsers);
userRoutes.get('/:username', verifyJWT, userMiddleware, userController.getUser);
userRoutes.get('/:username/posts', verifyJWT, userMiddleware, userController.getUserPosts);
userRoutes.get('/:username/experiences', verifyJWT, userMiddleware, userController.getUserExperiences);
userRoutes.get('/:username/userskills', verifyJWT, userMiddleware, userController.getUserSkills);
userRoutes.get('/:username/educations', verifyJWT, userMiddleware, userController.getUserEducations);
userRoutes.get('/:username/certificates', verifyJWT, userMiddleware, userController.getUserCertificates);
userRoutes.post('/:username/follows', verifyJWT, userMiddleware, userController.followToggle);
userRoutes.post('/userskills', verifyJWT, userController.addSkills);
userRoutes.post('/experiences', verifyJWT, userController.addExperience);
userRoutes.post('/experiencesskills', verifyJWT, userController.addExperienceSkill);
userRoutes.post('/educations', verifyJWT, userController.addEducation);
userRoutes.post('/certificates', verifyJWT, userController.addCertificate);
userRoutes.put('/', verifyJWT, userController.updateUser);
userRoutes.put('/avatar', verifyJWT, userMiddleware, upload.single('avatar'), userController.updateAvatar);
userRoutes.put('/cover', verifyJWT, userMiddleware, upload.single('cover'), userController.updateCover);
userRoutes.put('/experiences/:id', verifyJWT, userController.updateExperience);
userRoutes.put('/userskills/:id', verifyJWT, userController.updateUserSkills);
userRoutes.put('/educations/:id', verifyJWT, userController.updateEducation);
userRoutes.put('/certificates/:id', verifyJWT, userController.updateCertificate);
userRoutes.delete('/', verifyJWT, userController.deleteUser);
userRoutes.delete('/userskills/:id', verifyJWT, userController.deleteUserSkills);
userRoutes.delete('/experiences/:id', verifyJWT, userController.deleteExperience);
userRoutes.delete('/experiencesskills', verifyJWT, userController.deleteExperienceSkill);
userRoutes.delete('/educations/:id', verifyJWT, userController.deleteEducation);
userRoutes.delete('/certificates/:id', verifyJWT, userController.deleteCertificate);